name: "check_scheduler"

on:
  schedule:
    - cron: '29 9 * * 1-5'  # 23:20 KST
  workflow_dispatch:
  workflow_call:
    outputs:
      changed: 
        value: ${{ jobs.update-submodules.outputs.changed}}

jobs:
  update-submodules:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo ssw-atom with submodules
        run: |
          echo inputs ${{github.ref_name}}
          echo schedule ${{github.ref_name}}
